app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.index, name='index'),
#path('bruttennete',views.calculate, name='bruttennete'),
]

maashesap/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hesapla', include('app.urls') ,name='app'),
    path('', include('user.urls'),name='user'),
]
handler404 = 'user.views.handler404'

user/urls.py
from django.contrib import admin
from django.urls import path,include
from. import views
from django.conf.urls.static import static
from django.conf import settings

app_name='user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.index, name='homepage'),
    path('companyregister/', views.companyregister, name='companyregister'),
    path('companys/', views.listcompany, name='listcompany'),
    path('companys/<int:id>', views.detailcompany, name='detailcompany'),
    path('companys/<int:id>/addemp', views.calisanregister, name='calisanregister'),
    path('companys/<int:id>/listemp', views.listemployee, name='employeelist'),
    path('listemp/<int:id>', views.detailemployee, name='employeedetail'),
    path('addmaas/<int:id>', views.addmaas, name='addmaas'),
    path('maasdetail/<int:id>/<int:year>', views.maasdetail, name='maasdetail'),
    path('maasupdate/<int:id>/<int:maasid>',views.update_maas,name='maasupdate'),
    path('updatebymonth/<int:id>/<int:maasid>/<str:month>',views.updatebymonth,name='updatebymonth'),
    path('updateemp/<int:id>',views.update_emp,name='updateemp'),
    path('updatecompany/<int:id>',views.companyupdate,name='updatecompany'),
    path('registertype/', views.select_register_type, name='registertype'),
    path('registerwcomp/', views.register_with_company, name='register1'),
    path('senddatabase/<int:id>/<int:year>', views.getlist, name='senddatabase'),
    path("searche/<int:id>/",  views.searchemp, name="search"),
    path("searchc/",  views.searchcomp, name="searchc"),
    path("createpdf/<int:id>",  views.createpdf, name="pdf"),
    path("subelist/<int:id>",  views.listsube, name="subelist"),
    path("subelist/<int:id>/addsube",  views.suberegister, name="addsube"),
    path("updatesube/<int:id>",  views.updatesube, name="updatesube"),
    path("mycompany/",  views.list_malisirket_detail, name="malisirketdetail"),
    path("mycompany/addemp",  views.addmalimusavir, name="addmalimusavir"),
    path("checkusername/",  views.checkusername, name="checkusername"),
    path("addcompwurl/<slug:slug>",  views.addcompwithurl, name="addcompwithurl"),

    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'user.views.handler404'

user/views.py
import datetime
from gc import get_objects
from http.client import HTTPResponse
from tokenize import group
import uuid
from django.shortcuts import render,redirect,get_object_or_404
from .forms import RegisterForm,LoginForm,SirketRegisterForm,CalisanRegisterForm,MaasRegisterForm,monthform,calisanturform,engelliform,MaliMusavirRegisterForm,denemeform,SubeRegisterForm,malisirketRegisterForm,employeelistaylar,sgkisyeriregisterform,iskurregisterform
from django.contrib import messages
from django.contrib.auth.models import User,Group
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.decorators import login_required,permission_required, user_passes_test
from django.http import HttpResponseNotFound
from django.core.exceptions import ObjectDoesNotExist
from .models import maas,sirket,calisan,mali_musavir,bordro,sube,mali_sirket,subs,maintence,iskur,sgkisyeri
from django.http import HttpResponse
from app.views import autouser,sendlist
from app.tekayhesaplama import hesaplama1
from django.db.models import Q
from django.template import RequestContext

from django.urls import reverse
import datetime

from datetime import datetime, timedelta

@login_required(login_url='user:login')
def index(request):
    sirket1=[]
    sirket2=None
    if maintence.objects.first().maintence:
        return render(request,'maintence.html')

    if request.user.groups.filter(name='admin').exists():
        calisantab=False
        sirkettab=False
        user=None
        sirket1=sirket.objects.all()


    else :

        if request.user.groups.filter(name='mali_musavir').exists():
            calisantab=False
            user=mali_musavir.objects.get(mali_musavir_id=request.user)
            malisirket=mali_sirket.objects.get(id=user.mali_sirket_id.id)

            sirkettab=False
            sirket1=malisirket.mali_sirket_bagli_sirketler.all()


        elif request.user.groups.filter(name='muhasebe').exists():
            calisantab=True
            sirkettab=False
            user=calisan.objects.get(calisan_id=request.user)
            sirket1.append(sirket.objects.get(id=user.calisan_sirket_id.id).id)
            sirket2=sirket1[0]

           
        else:
            calisantab=False
            sirkettab=False
            user=calisan.objects.get(calisan_id=request.user)
            sirket1.append(sirket.objects.get(id=user.calisan_sirket_id.id).id)
            sirket2=sirket1[0]

    mainpage=True

    dolar=getdolar()[0][1]
    euro=geteuro()[0][1]


    context={
        'sirket_id':sirket2,
        'calisantab':calisantab,
        'sirkettab':sirkettab,
        'user1':user,
        'mainpage':mainpage,
        'dolar':dolar,
        'euro':euro,
        'sirketedit':False,
        'subeedit':False,



    }
    return render(request,'homepage.html',context)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
def getdolar():
    startDate= ""
    endDate=""
    if int(datetime.now().hour)<15 and int(datetime.now().minute)<30:
        date_today = (datetime.today()-timedelta(days=1)).date().strftime("%d-%m-%Y")

        startDate=date_today


        endDate=date_today

    else:
        date_today = (datetime.today()).date().strftime("%d-%m-%Y")
        startDate=date_today

        endDate=date_today


    i=1
    while True:

        series ="TP.DK.USD.A.YTL"
        series_name="Dolar_Kuru"
        typee="csv"
        key="dJqoNMHhsC"
        aggregationTypes="avg"
        formulas="0"
        frequency = "2"
        url= 'https://evds2.tcmb.gov.tr/service/evds/series={}&startDate={}&endDate={}&type={}&key={}&aggregationTypes={}&formulas={}&frequency={}'.format(series,
        startDate,endDate,typee,key,aggregationTypes,formulas,frequency)
        try:
            dolar = pd.read_csv(url)
            break
        except:
            date_today = (datetime.today()-timedelta(days=i)).date().strftime("%d-%m-%Y")
            startDate= date_today
            endDate=date_today
            i+=1






    dolar1=dolar.values.tolist()


    return dolar1
def geteuro():
    startDate= ""
    endDate=""
    if int(datetime.now().hour)<15 and int(datetime.now().minute)<30:
        date_today = (datetime.today()-timedelta(days=1)).date().strftime("%d-%m-%Y")
        startDate=date_today


        endDate=date_today

    else:
        date_today = (datetime.today()).date().strftime("%d-%m-%Y")
        startDate=date_today
        endDate=date_today

    i=1
    while True:
        series ="TP.DK.EUR.A.YTL"
        series_name="Euro_Kuru"
        typee="csv"
        key="dJqoNMHhsC"
        aggregationTypes="avg"
        formulas="0"
        frequency = "2"
        url= 'https://evds2.tcmb.gov.tr/service/evds/series={}&startDate={}&endDate={}&type={}&key={}&aggregationTypes={}&formulas={}&frequency={}'.format(series,
        startDate,endDate,typee,key,aggregationTypes,formulas,frequency)
        try:
            euro = pd.read_csv(url)
            break
        except:
            date_today = (datetime.today()-timedelta(days=i)).date().strftime("%d-%m-%Y")
            startDate= date_today
            endDate=date_today
            i+=1

    euro1=euro.values.tolist()

    return euro1

def hesapla(request,id,year,tesvik,engelli,indirim):
    employee=calisan.objects.get(id=id)
    user1=User.objects.get(id=employee.calisan_id_id)
    maass=maas.objects.filter(calisan_id=employee,yil=year)

    argegun=[]
    ucret=[]
    gun=[]
    gun.append(maass[0].gunsayisi1)
    gun.append(maass[0].gunsayisi2)
    gun.append(maass[0].gunsayisi3)
    gun.append(maass[0].gunsayisi4)
    gun.append(maass[0].gunsayisi5)
    gun.append(maass[0].gunsayisi6)
    gun.append(maass[0].gunsayisi7)
    gun.append(maass[0].gunsayisi8)
    gun.append(maass[0].gunsayisi9)
    gun.append(maass[0].gunsayisi10)
    gun.append(maass[0].gunsayisi11)
    gun.append(maass[0].gunsayisi12)
    argegun.append(maass[0].argegun1)
    argegun.append(maass[0].argegun2)
    argegun.append(maass[0].argegun3)
    argegun.append(maass[0].argegun4)
    argegun.append(maass[0].argegun5)
    argegun.append(maass[0].argegun6)
    argegun.append(maass[0].argegun7)
    argegun.append(maass[0].argegun8)
    argegun.append(maass[0].argegun9)
    argegun.append(maass[0].argegun10)
    argegun.append(maass[0].argegun11)
    argegun.append(maass[0].argegun12)
    ucret.append(maass[0].maas_tutari1)
    ucret.append(maass[0].maas_tutari2)
    ucret.append(maass[0].maas_tutari3)
    ucret.append(maass[0].maas_tutari4)
    ucret.append(maass[0].maas_tutari5)
    ucret.append(maass[0].maas_tutari6)
    ucret.append(maass[0].maas_tutari7)
    ucret.append(maass[0].maas_tutari8)
    ucret.append(maass[0].maas_tutari9)
    ucret.append(maass[0].maas_tutari10)
    ucret.append(maass[0].maas_tutari11)
    ucret.append(maass[0].maas_tutari12)
    parabirimi=maass[0].para_birimi



    return autouser(request,ucret,gun,argegun,tesvik,engelli,indirim,year,parabirimi,False)

def getlist(request,id,year,):
    if request.user.groups.filter(name='admin').exists():
        pass
    elif request.user.groups.filter(name='mali_musavir').exists():
        if sirket.objects.get(sirket_mali_musavir_id=request.user,id=calisan.objects.get(id=id).calisan_sirket_id.id).sirket_mali_musavir_id!=request.user:
            return HttpResponseNotFound('<h1>Page not found</h1>')
    elif request.user.groups.filter(name='calisan').exists():
        if request.user.id != calisan.objects.get(id=id).calisan_id_id:
            return HttpResponseNotFound("Yetkisiz Erişim")

    employee=calisan.objects.filter(id=id)
    tesvik=employee[0].calisan_tesvik
    engelli=employee[0].calisan_engelli
    indirim=employee[0].calisan_indirim





    return getlist1(request,id,year,tesvik,engelli,indirim)


def getlist1(request,id,year,tesvik,engelli,indirim):
    employee=calisan.objects.get(id=id)
    maass=maas.objects.filter(calisan_id=employee,yil=year)
    ucret=[]
    parabirimi=maass[0].para_birimi
    argegun=[]
    gun=[]
    gun.append(maass[0].gunsayisi1)
    gun.append(maass[0].gunsayisi2)
    gun.append(maass[0].gunsayisi3)
    gun.append(maass[0].gunsayisi4)
    gun.append(maass[0].gunsayisi5)
    gun.append(maass[0].gunsayisi6)
    gun.append(maass[0].gunsayisi7)
    gun.append(maass[0].gunsayisi8)
    gun.append(maass[0].gunsayisi9)
    gun.append(maass[0].gunsayisi10)
    gun.append(maass[0].gunsayisi11)
    gun.append(maass[0].gunsayisi12)
    argegun.append(maass[0].argegun1)
    argegun.append(maass[0].argegun2)
    argegun.append(maass[0].argegun3)
    argegun.append(maass[0].argegun4)
    argegun.append(maass[0].argegun5)
    argegun.append(maass[0].argegun6)
    argegun.append(maass[0].argegun7)
    argegun.append(maass[0].argegun8)
    argegun.append(maass[0].argegun9)
    argegun.append(maass[0].argegun10)
    argegun.append(maass[0].argegun11)
    argegun.append(maass[0].argegun12)
    ucret.append(maass[0].maas_tutari1)
    ucret.append(maass[0].maas_tutari2)
    ucret.append(maass[0].maas_tutari3)
    ucret.append(maass[0].maas_tutari4)
    ucret.append(maass[0].maas_tutari5)
    ucret.append(maass[0].maas_tutari6)
    ucret.append(maass[0].maas_tutari7)
    ucret.append(maass[0].maas_tutari8)
    ucret.append(maass[0].maas_tutari9)
    ucret.append(maass[0].maas_tutari10)
    ucret.append(maass[0].maas_tutari11)
    ucret.append(maass[0].maas_tutari12)
    empmaas=list(sendlist(request,ucret,gun,argegun,tesvik,engelli,indirim,year,parabirimi))



    return empmaas
def select_register_type(request):
    return render(request,'registertype.html')

def register(request):
    form = RegisterForm(request.POST or None)
    form2=calisanturform(request.POST or None)
    form3=engelliform(request.POST or None)
    form4=MaliMusavirRegisterForm(request.POST or None,request.FILES or None)
    form5=malisirketRegisterForm(request.POST or None)

app/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}

        {% comment %} <div class="col-md-6 offset-md-3">
            <h3>Giriş Yap</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
                <br>
                <a href="{% url 'user:registertype' %}">Kayıt Olmak için tıklayın</a>
                <br>
                <br>
            
                {{captcha}}
      
                <button type="submit" class=" btn btn-danger">Giriş Yap</button>
              
              
            </form>
            <br>
           
            
        </div> {% endcomment %}


        <style>
           
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,800');

* {
	box-sizing: border-box;
}

body {
	background: #f6f5f7;
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	font-family: 'Montserrat', sans-serif;
	height: 100vh;
	margin: -20px 0 50px;
    overflow: hidden;
}

h1 {
	font-weight: bold;
	margin: 0;
}

h2 {
	text-align: center;
}

p {
	font-size: 14px;
	font-weight: 100;
	line-height: 20px;
	letter-spacing: 0.5px;
	margin: 20px 0 30px;
}

span {
	font-size: 12px;
}

a {
	color: #333;
	font-size: 14px;
	text-decoration: none;
	margin: 15px 0;
}

button {
	border-radius: 20px;
	border: 1px solid #FF4B2B;
	background-color: #FF4B2B;
	color: #FFFFFF;
	font-size: 12px;
	font-weight: bold;
	padding: 12px 45px;
	letter-spacing: 1px;
	text-transform: uppercase;
	transition: transform 80ms ease-in;
}

button:active {
	transform: scale(0.95);
}

button:focus {
	outline: none;
}

button.ghost {
	background-color: transparent;
	border-color: #FFFFFF;
}

form {
	background-color: #FFFFFF;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 50px;
	height: 100%;
	text-align: center;
}

input {
	background-color: #eee;
	border: none;
	padding: 12px 15px;
	margin: 8px 0;
	width: 100%;
}

.container {
	background-color: #fff;
	border-radius: 10px;
  	box-shadow: 0 14px 28px rgba(0,0,0,0.25), 
			0 10px 10px rgba(0,0,0,0.22);
	position: relative;
	overflow: hidden;
	width: 768px;
	max-width: 100%;
	min-height: 480px;
}

.form-container {
	position: absolute;
	top: 0;
	height: 100%;
	transition: all 0.6s ease-in-out;
}

.sign-in-container {
	left: 0;
	width: 50%;
	z-index: 2;
}

.container.right-panel-active .sign-in-container {
	transform: translateX(100%);
}

.sign-up-container {
	left: 0;
	width: 50%;
	opacity: 0;
	z-index: 1;
}

.container.right-panel-active .sign-up-container {
	transform: translateX(100%);
	opacity: 1;
	z-index: 5;
	animation: show 0.6s;
}

@keyframes show {
	0%, 49.99% {
		opacity: 0;
		z-index: 1;
	}
	
	50%, 100% {
		opacity: 1;
		z-index: 5;
	}
}

.overlay-container {
	position: absolute;
	top: 0;
	left: 50%;
	width: 50%;
	height: 100%;
	overflow: hidden;
	transition: transform 0.6s ease-in-out;
	z-index: 100;
}

.container.right-panel-active .overlay-container{
	transform: translateX(-100%);
}

.overlay {
	background: #FF416C;
	background: -webkit-linear-gradient(to right, #FF4B2B, #FF416C);
	background: linear-gradient(to right, #FF4B2B, #FF416C);
	background-repeat: no-repeat;
	background-size: cover;
	background-position: 0 0;
	color: #FFFFFF;
	position: relative;
	left: -100%;
	height: 100%;
	width: 200%;
  	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.container.right-panel-active .overlay {
  	transform: translateX(50%);
}

.overlay-panel {
	position: absolute;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	padding: 0 40px;
	text-align: center;
	top: 0;
	height: 100%;
	width: 50%;
	transform: translateX(0);
	transition: transform 0.6s ease-in-out;
}

.overlay-left {
	transform: translateX(-20%);
}

.container.right-panel-active .overlay-left {
	transform: translateX(0);
}

.overlay-right {
	right: 0;
	transform: translateX(0);
}

.container.right-panel-active .overlay-right {
	transform: translateX(20%);
}

.social-container {
	margin: 20px 0;
}

.social-container a {
	border: 1px solid #DDDDDD;
	border-radius: 50%;
	display: inline-flex;
	justify-content: center;
	align-items: center;
	margin: 0 5px;
	height: 40px;
	width: 40px;
}

footer {
    background-color: #222;
    color: #fff;
    font-size: 14px;
    bottom: 0;
    position: fixed;
    left: 0;
    right: 0;
    text-align: center;
    z-index: 999;
}

footer p {
    margin: 10px 0;
}

footer i {
    color: red;
}

footer a {
    color: #3c97bf;
    text-decoration: none;
}
.btn-primary, .btn-primary:hover, .btn-primary:active, .btn-primary:visited {
    background-color:  #FF4B2B !important;
}
            </style>
       

            <div class="container" id="container">
                <div class="form-container sign-up-container">
                    <form action="#" >
                        <h1>Kayıt Ol</h1>
                        <div class="social-container">
                            <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                            <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                            <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                        
                        <a class="btn btn-primary" href="{% url 'user:register'  %}" role="button">Mali Müşavir Kayıt</a>
                        <a class="btn btn-primary" href="{% url 'user:register1'  %}" role="button">Muhasebe Kayıt</a>
                    </form>
                </div>
                <div class="form-container sign-in-container">
                    <form method="post">
                        {% csrf_token %}
                        <h1>Giriş Yap</h1>
                        <br>

                        <input type="username" name="username" placeholder="Kullanıcı Adı" />
                        <input type="password" name="password" placeholder="Şifre" />
                        <br>
                        <button>Giriş Yap</button>
                    </form>
                </div>
                <div class="overlay-container">
                    <div class="overlay">
                        <div class="overlay-panel overlay-left">
                            <h1>Zaten Kayıt Oldunuz Mu?</h1>
                            <p>Giriş Yapmak İçin Butona Basın</p>
                            <button class="ghost" id="signIn">Giriş Yap</button>
                        </div>
                        <div class="overlay-panel overlay-right">
                            <h1>Henüz Kayıt Olmadınız Mı?</h1>
                            <p>Kayıt Olmak Butona Basmak Kadar Kolay</p>
                            <button class="ghost" id="signUp">Kayıt Ol</button>
                        </div>
                    </div>
                </div>
            </div>
            
            <script>
                const signUpButton = document.getElementById('signUp');
const signInButton = document.getElementById('signIn');
const container = document.getElementById('container');

signUpButton.addEventListener('click', () => {
	container.classList.add("right-panel-active");
});

signInButton.addEventListener('click', () => {
	container.classList.remove("right-panel-active");
});
            </script>



    

    {% endblock %}

app/templates/user/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    {% block content %}


        <div class="col-md-6 offset-md-3">
            <h3>Kayıt Ol</h3>
            <hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="border rounded p-2 border-secondary"> <h4> Oturum Bilgileriniz</h4> <br> {{form|crispy}}</div>
    <br>
    <div class="border rounded p-2 border-secondary"> <h4> Şirket Bilgileriniz</h4> <br> {{form5|crispy}}</div>
    <br>
    <div class="border rounded p-2 border-secondary"> <h4> Sizin Hakkınızda</h4> <br> {{form4|crispy}} <br> {{form2|crispy}} <br> {{form3|crispy}}</div>
    


    
    <br>
    <button type="submit" class="btn btn-danger">Kayıt ol</button>
    <br>
    <br>
    <br>
</form>
        </div>

    {% endblock %}