app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.index, name='index'),
#path('bruttennete',views.calculate, name='bruttennete'),
]

maashesap/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hesapla', include('app.urls') ,name='app'),
    path('', include('user.urls'),name='user'),
]
handler404 = 'user.views.handler404'

user/urls.py
from django.contrib import admin
from django.urls import path,include
from. import views
from django.conf.urls.static import static
from django.conf import settings

app_name='user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('', views.index, name='homepage'),
    path('companyregister/', views.companyregister, name='companyregister'),
    path('companys/', views.listcompany, name='listcompany'),
    path('companys/<int:id>', views.detailcompany, name='detailcompany'),
    path('companys/<int:id>/addemp', views.calisanregister, name='calisanregister'),
    path('companys/<int:id>/listemp', views.listemployee, name='employeelist'),
    path('listemp/<int:id>', views.detailemployee, name='employeedetail'),
    path('addmaas/<int:id>', views.addmaas, name='addmaas'),
    path('maasdetail/<int:id>/<int:year>', views.maasdetail, name='maasdetail'),
    path('maasupdate/<int:id>/<int:maasid>',views.update_maas,name='maasupdate'),
    path('updatebymonth/<int:id>/<int:maasid>/<str:month>',views.updatebymonth,name='updatebymonth'),
    path('updateemp/<int:id>',views.update_emp,name='updateemp'),
    path('updatecompany/<int:id>',views.companyupdate,name='updatecompany'),
    path('registertype/', views.select_register_type, name='registertype'),
    path('registerwcomp/', views.register_with_company, name='register1'),
    path('senddatabase/<int:id>/<int:year>', views.getlist, name='senddatabase'),
    path("searche/<int:id>/",  views.searchemp, name="search"),
    path("searchc/",  views.searchcomp, name="searchc"),
    path("createpdf/<int:id>",  views.createpdf, name="pdf"),
    path("subelist/<int:id>",  views.listsube, name="subelist"),
    path("subelist/<int:id>/addsube",  views.suberegister, name="addsube"),
    path("updatesube/<int:id>",  views.updatesube, name="updatesube"),
    path("mycompany/",  views.list_malisirket_detail, name="malisirketdetail"),
    path("mycompany/addemp",  views.addmalimusavir, name="addmalimusavir"),
    path("checkusername/",  views.checkusername, name="checkusername"),
    path("addcompwurl/<slug:slug>",  views.addcompwithurl, name="addcompwithurl"),

    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'user.views.handler404'

app/templates/addcompany.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Şirket Ekle</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
                <br>
                <button type="submit" class=" btn btn-danger">Ekle</button>
              
              
            </form>
            <br>
           
            
        </div>
      </div>
    

    {% endblock %}

app/templates/addemployee.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Çalışan Ekle</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                <input type="text" name="username1" id="username" class="form-control" placeholder="Kullanıcı Adı" hx-post="{% url 'user:checkusername' %}" hx-target="#username-check" hx-trigger="keyup" required>
                <div id="username-check"></div>
                <br>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


  <input type="password" name="password1" id="password1" class="form-control" placeholder="Şifre" required>

<br>

  <input type="password" name="confirm_password1" id="confirm_password1" class="form-control" placeholder="Şifre Doğrulama"required >
  <span id='message'></span>
<br>
<script>
$('#password1, #confirm_password1').on('keyup', function () {
    if ($('#password1').val() == $('#confirm_password1').val() && $('#password1').val() != "") {
      $('#message').html('Doğrulandı').css('color', 'green');
    } else 
      $('#message').html('Şifreler Uyuşmuyor').css('color', 'red');
  });
</script>
                {% comment %} {{ form|crispy}} {% endcomment %}
                {{ calisan|crispy}} 
                {{ form1|crispy}}
                {{ form2|crispy}}
                <br>
                <button type="submit" class=" btn btn-danger">Ekle</button>
              
              
            </form>
            <br>
           
            
        </div>
      </div>
    

    {% endblock %}

app/templates/calculated.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
  

<style>
  p{
    font-size: 11px;
    font-weight: bold;
  }
  table{
    height:100%;width:100%; position: absolute; top: 0; bottom: 0; left: 0; right: 0;
  }

 
</style>

<div class="container">

  <div class="table-responsive">
  <table  class="table table-bordered table-dark  table-sm table-striped m-10px">
    <thead>
      <tr>
        <th scope="col"><p> Aylar</p></th>
        <th scope="col"><p>Brüt Ücret</p></th>
        <th scope="col"><p>Çalışılan Gün</p></th>
        <th scope="col"><p>Arge Gün</p></th>
        <th scope="col"><p>Bordroya Esas Brüt Ücret</p></th>
        <th scope="col"><p>Sgk Matrahı</p></th>
        <th scope="col"><p style="color:red">SGK Kesintisi</p></th>
        <th scope="col"><p style="color:red">İşsizlik Kesintisi</p></th>
        <th scope="col"><p>Vergi Dilimi</p></th>
        <th scope="col"><p>İstisna Öncesi Gelir Vergisi</p></th>
        <th scope="col"><p>İstisna Öncesi Damga Vergisi</p></th>
        <th scope="col"><p>Vergi Matrahı</p></th>
        <th scope="col"><p>Kumulatif Vergi Matrahi</p></th>
        <th scope="col"><p>İstisna Öncesi Gelir Vergisi</p></th>
        <th scope="col"><p>Asgari Vergi Matrah</p></th>
        <th scope="col"><p>Kumulatif Asgari Ücret</p></th>
        <th scope="col"><p style="color:#12B9D6">Asgari Gelir Vergisi İstisnasi</p></th>
        <th scope="col"><p style="color:#12B9D6">Asgari Damga Vergisi İstisnasi</p></th>
        <th scope="col"><p style="color:red">Damga Vergisi</p></th>
        <th scope="col"><p style="color:red">Gelir Vergisi</p></th>
        <th scope="col"><p style="color:#12B9D6">Gelir Vergisi İstisnası</p></th>
        <th scope="col"><p style="color:#12B9D6">Damga Vergisi İstisnası</p></th>
        <th scope="col"><p>Net Ücret</p></th>
        <th scope="col"><p style="color:teal">İşveren SGK Kesintisi</p></th>
        <th scope="col"><p style="color:teal">İşveren İşsizlik Kesintisi</p></th>
        <th scope="col"><p>Toplam Sgk</p></th>
        <th scope="col"><p style="color:teal">Toplam Maliyet</p></th>
        <th scope="col"><p>Sgk İstisnası</p></th>
        <th scope="col"><p style="color:orange">Ödenecek SGK</p></th>
        <th scope="col"><p style="color:orange">Ödenecek Gelir</p></th>
        <th scope="col"><p style="color:orange">Ödenecek Damga Vergisi</p></th>
        
      </tr>
    </thead>
    <tbody>
  
  
   {% for maas in maaslar %}
   <tr style="height:60px">
  
        {% if forloop.last %}
        <td><p style="color:#3bd90c">{{ maas.0 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.19 }}</p></td>
        <td><p style="color:#3bd90c">{{maas.2}}</p></td>
        <td><p style="color:#3bd90c">{{maas.30}}</p></td>
        <td><p style="color:#3bd90c">{{maas.1}}</p></td>
        
        <td><p style="color:#3bd90c">{{maas.3}}</p></td>
        <td><p style="color:#3bd90c">{{maas.4}}</p></td>
        <td><p style="color:#3bd90c">{{maas.5}}</p></td>
        <td><p style="color:#3bd90c">{{maas.25}}</p></td>
        <td><p style="color:#3bd90c">{{maas.24}}</p></td>
        <td><p style="color:#3bd90c">{{maas.26}}</p></td>
        <td><p style="color:#3bd90c">{{maas.6}}</p></td>
        <td><p style="color:#3bd90c">{{ maas.7 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.8 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.9 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.10 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.11 }}</p></td>
        <td><p style="color:#3bd90c">{{ maas.27 }}</p></td>
        <td><p style="color:#3bd90c">{{maas.12}}</p></td>
        <td><p style="color:#3bd90c">{{maas.13}}</p></td>
        <td><p style="color:#3bd90c">{{maas.28}}</p></td>
        <td><p style="color:#3bd90c">{{maas.29}}</p></td>
        <td><p style="color:#3bd90c">{{ maas.14 }}</p></td>
        <td><p style="color:#3bd90c">{{maas.15}}</p></td>
        <td><p style="color:#3bd90c">{{maas.16}}</p></td>
        <td><p style="color:#3bd90c">{{ maas.17 }}</p></td>
        <td><p style="color:#3bd90c">{{maas.18}}</p></td>
        <td><p style="color:#3bd90c">{{ maas.20 }}</p></td>
        <td><p style="color:#3bd90c">{{maas.21}}</p></td>
        <td><p style="color:#3bd90c">{{maas.22}}</p></td>
        <td><p style="color:#3bd90c">{{maas.23}}</p></td>
        {% else %}
        <td><p>{{ maas.0 }}</p></td>
        <td><p>{{ maas.19 }}</p></td>
        <td><p>{{maas.2}}</p></td>
        <td><p>{{maas.30}}</p></td>
        <td><p>{{maas.1}}</p></td>
        
        <td><p>{{maas.3}}</p></td>
        <td><p style="color:red">{{maas.4}}</p></td>
        <td><p style="color:red">{{maas.5}}</p></td>
        <td><p>{{maas.25}}</p></td>
        <td><p>{{maas.24}}</p></td>
        <td><p>{{maas.26}}</p></td>
        <td><p>{{maas.6}}</p></td>
        <td><p>{{ maas.7 }}</p></td>
        <td><p>{{ maas.8 }}</p></td>
        <td><p>{{ maas.9 }}</p></td>
        <td><p>{{ maas.10 }}</p></td>
        <td><p style="color:#12B9D6">{{ maas.11 }}</p></td>
        <td><p style="color:#12B9D6">{{ maas.27 }}</p></td>
        <td><p style="color:red">{{maas.12}}</p></td>
        <td><p style="color:red">{{maas.13}}</p></td>
        <td><p style="color:#12B9D6">{{maas.28}}</p></td>
        <td><p style="color:#12B9D6">{{maas.29}}</p></td>
        <td><p>{{ maas.14 }}</p></td>
        <td><p style="color:teal">{{maas.15}}</p></td>
        <td><p style="color:teal">{{maas.16}}</p></td>
        <td><p>{{ maas.17 }}</p></td>
        <td><p style="color:teal">{{maas.18}}</p></td>
        <td><p>{{ maas.20 }}</p></td>
        <td><p style="color:orange">{{maas.21}}</p></td>
        <td><p style="color:orange">{{maas.22}}</p></td>
        <td><p style="color:orange">{{maas.23}}</p></td>
        {% endif %}
  
       
       
  
   
      </tr>
     {% endfor %}
   
  </tbody>
</table>
</div>


<body>

app/templates/companyupdate.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Şirket Düzenle</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
               
                
                <br>
                <button type="submit" class=" btn btn-danger">Düzenle</button>
              
              
            </form>
            <br>
           
            
        </div>
      </div>
    

    {% endblock %}

app/templates/custom404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<style>
    @import url('https://fonts.googleapis.com/css?family=Montserrat:400,600,700');
@import url('https://fonts.googleapis.com/css?family=Catamaran:400,800');
.error-container {
  text-align: center;
  font-size: 180px;
  font-family: 'Catamaran', sans-serif;
  font-weight: 800;
  margin: 20px 15px;
}
.error-container > span {
  display: inline-block;
  line-height: 0.7;
  position: relative;
  color: #FFB485;
}
.error-container > span {
  display: inline-block;
  position: relative;
  vertical-align: middle;
}
.error-container > span:nth-of-type(1) {
  color: #D1F2A5;
  animation: colordancing 4s infinite;
}
.error-container > span:nth-of-type(3) {
  color: #F56991;
  animation: colordancing2 4s infinite;
}
.error-container > span:nth-of-type(2) {
  width: 120px;
  height: 120px;
  border-radius: 999px;
}
.error-container > span:nth-of-type(2):before,
.error-container > span:nth-of-type(2):after {
	border-radius: 0%;
	content:"";
	position: absolute;
	top: 0; left: 0;
	width: inherit; height: inherit;
  border-radius: 999px;
	box-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),
				inset 0 30px 0 rgba(239, 250, 180, 0.4),
				inset -30px 0 0 rgba(255, 196, 140, 0.4),	
				inset 0 -30px 0 rgba(245, 105, 145, 0.4);
  animation: shadowsdancing 4s infinite;
}
.error-container > span:nth-of-type(2):before {
	-webkit-transform: rotate(45deg);
	   -moz-transform: rotate(45deg);
			transform: rotate(45deg);
}

.screen-reader-text {
    position: absolute;
    top: -9999em;
    left: -9999em;
}
@keyframes shadowsdancing {
  0% {
    box-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),
				inset 0 30px 0 rgba(239, 250, 180, 0.4),
				inset -30px 0 0 rgba(255, 196, 140, 0.4),	
				inset 0 -30px 0 rgba(245, 105, 145, 0.4);
  }
  25% {
    box-shadow: inset 30px 0 0 rgba(245, 105, 145, 0.4),
				inset 0 30px 0 rgba(209, 242, 165, 0.4),
				inset -30px 0 0 rgba(239, 250, 180, 0.4),	
				inset 0 -30px 0 rgba(255, 196, 140, 0.4);
  }
  50% {
     box-shadow: inset 30px 0 0 rgba(255, 196, 140, 0.4),
				inset 0 30px 0 rgba(245, 105, 145, 0.4),
				inset -30px 0 0 rgba(209, 242, 165, 0.4),	
				inset 0 -30px 0 rgba(239, 250, 180, 0.4);
  }
  75% {
   box-shadow: inset 30px 0 0 rgba(239, 250, 180, 0.4),
				inset 0 30px 0 rgba(255, 196, 140, 0.4),
				inset -30px 0 0 rgba(245, 105, 145, 0.4),	
				inset 0 -30px 0 rgba(209, 242, 165, 0.4);
  }
  100% {
    box-shadow: inset 30px 0 0 rgba(209, 242, 165, 0.4),
				inset 0 30px 0 rgba(239, 250, 180, 0.4),
				inset -30px 0 0 rgba(255, 196, 140, 0.4),	
				inset 0 -30px 0 rgba(245, 105, 145, 0.4);
  }
}
@keyframes colordancing {
  0% {
    color: #D1F2A5;
  }
  25% {
    color: #F56991;
  }
  50% {
    color: #FFC48C;
  }
  75% {
    color: #EFFAB4;
  }
  100% {
    color: #D1F2A5;
  }
}
@keyframes colordancing2 {
  0% {
    color: #FFC48C;
  }
  25% {
    color: #EFFAB4;
  }
  50% {
    color: #D1F2A5;
  }
  75% {
    color: #F56991;
  }
  100% {
    color: #FFC48C;
  }
}

/* demo stuff */
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
body {
  background-color: #416475;
  margin-bottom: 50px;
}
html, button, input, select, textarea {
    font-family: 'Montserrat', Helvetica, sans-serif;
    color: #92a4ad;
}
h1 {
  text-align: center;
  margin: 30px 15px;
}
.zoom-area { 
  max-width: 490px;
  margin: 30px auto 30px;
  font-size: 19px;
  text-align: center;
}
.link-container {
  text-align: center;
}
a.more-link {
  text-transform: uppercase;
  font-size: 13px;
    background-color: #92a4ad;
    padding: 10px 15px;
    border-radius: 0;
    color: #416475;
    display: inline-block;
    margin-right: 5px;
    margin-bottom: 5px;
    line-height: 1.5;
    text-decoration: none;
  margin-top: 50px;
  letter-spacing: 1px;
}
</style>

   
    <p class="zoom-area">Görünüşe Göre Yanlış Yerdesiniz</p>
    <section class="error-container">
      <span>4</span>
      <span><span class="screen-reader-text">0</span></span>
      <span>4</span>
    </section>
    <div class="link-container">
      <a target="_blank" href="{% url 'user:homepage'%}" class="more-link">Anasayfa</a>
    </div>
</body>
</html>

app/templates/employeedetail.html
{% extends "base.html" %}
{% load has_group %}
{% load crispy_forms_tags %}
{% block content %}

<h1>{{ employee.calisan_adi }} {{ employee.calisan_soyadi }}</h1>
<h1>TC : {{ employee.calisan_tc  }}</h1>
{% if request.user|has_group:"calisan" %}
{% else %}
<a class="btn btn-primary" href="{% url 'user:updateemp' employee.id  %}" role="button">Çalışan Düzenle</a>
<a class="btn btn-primary" href="{% url 'user:addmaas' employee.id  %}" role="button">Maaş Tablosu Ekle</a>
{% endif %}
<br>
<br>
<style>
  .dropdown-menu {
    width: 100%;
    }
  .dropdown {
      width: 100%;
      }
</style>


<div class="list-group">
    {% for maas in maass %}
    
    <a href="{% url 'user:maasdetail' id=employee.id year=maas.yil  %}" class="list-group-item list-group-item-action">{{maas.yil}} Yılına Ait Bordro Tablosu </a>
    
    {% if request.user|has_group:"calisan" %}
    {% else %}
    <br>

    <div class="row">
      <div class="col">
        <a class="btn btn-primary btn-block" href="{% url 'user:maasupdate' id=employee.id maasid=maas.id  %}" role="button">Düzenle</a>
      </div>
      <div class="col">
         <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Aya Göre Düzenle
    </button>
    <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
      {% for ay in aylar1 %}
      <a class="dropdown-item" href="{% url 'user:updatebymonth' id=employee.id maasid=maas.id month=ay %}" > {{ay}} </a>
      {% endfor %}
      
         
    </div>
    
      </div>
      
    </div>


    
   
 
  </div>
 
  {% endif %}
  <br>

<a class="btn btn-warning btn-block" href="{% url 'user:pdf' id=maas.id  %}" role="button">PDF Oluştur</a>

    {% endfor %}
    

  
   
  </div>



{% endblock %}

app/templates/homepage.html
{% extends "base.html" %}
{% load has_group %}
{% load crispy_forms_tags %}


{% block content %}

<div class="col-mb-6 mx-auto">


{% if request.user|has_group:"mali_musavir" %}
<h1>{{ user1.mali_musavir_adi }}</h1>
{% else %}
<h1>{{ user1.calisan_adi }} {{user1.calisan_soyadi}}</h1>
{% endif %}

              
</div>
    


{% endblock %}

app/templates/muhaseberegister.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}

        <div class="col-md-6 offset-md-3">
            <h3>Muhasebe Kayıt</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                <div class="border rounded p-2 border-secondary"> <h4> Oturum Bilgileriniz</h4> <br>
                    <input type="text" name="username1" id="username" class="form-control" placeholder="Kullanıcı Adı" hx-post="{% url 'user:checkusername' %}" hx-target="#username-check" hx-trigger="keyup" required>
                    <div id="username-check"></div>
                    <br>
                    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    
    
      <input type="password" name="password1" id="password1" class="form-control" placeholder="Şifre" required>
    
    <br>
    
      <input type="password" name="confirm_password1" id="confirm_password1" class="form-control" placeholder="Şifre Doğrulama"required >
      <span id='message'></span>
    <br>
    <script>
    $('#password1, #confirm_password1').on('keyup', function () {
        if ($('#password1').val() == $('#confirm_password1').val() && $('#password1').val() != "") {
          $('#message').html('Doğrulandı').css('color', 'green');
        } else 
          $('#message').html('Şifreler Uyuşmuyor').css('color', 'red');
      });
    </script>
                    
                    </div>
    <br>
    <div class="border rounded p-2 border-secondary"> <h4> Şirket Bilgileriniz</h4> <br> {{form3|crispy}}</div>

    <br>
    <div class="border rounded p-2 border-secondary"> <h4> Çalışan Hakkınızda</h4> <br> {{calisan|crispy}} <br> {{form1|crispy}} <br> {{form2|crispy}} </div>

    <br>

                
                
                
                
                
                
                
                <br>
                <button type="submit" class=" btn btn-danger">Kayıt ol</button>
              
              
            </form>
            <br>
           
            
        </div>




    {% endblock %}

app/templates/registertype.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<a class="btn btn-primary" href="{% url 'user:register'  %}" role="button">Mali Müşavir Kayıt</a>
<a class="btn btn-primary" href="{% url 'user:register1'  %}" role="button">Muhasebe Kayıt</a>

{% endblock %}

app/templates/updatemaas.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Maas</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
                
                
                <br>
                <button type="submit" class=" btn btn-danger">Düzenle</button>
              
              
            </form>
            <br>
           
            
        </div>
      </div>
    

    {% endblock %}

app/templates/updatesube.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
    
    {% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Şube Düzenle</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy}}
                {{ form2|crispy}}
                {{ form3|crispy}}
                <br>
                <button type="submit" class=" btn btn-danger">Düzenle</button>
              
              
            </form>
            <br>
           
            
        </div>
      </div>
    

    {% endblock %}